"""add student photo_url

Revision ID: e4af2a194e8d
Revises: ecc64213b0c5
Create Date: 2026-06-30 11:17:17.529890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4af2a194e8d'
down_revision: Union[str, None] = 'ecc64213b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; then drop it so the app controls the value.
    op.add_column(
        'students',
        sa.Column('photo_url', sa.String(length=255), nullable=False, server_default=''),
    )
    op.alter_column('students', 'photo_url', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'photo_url')
    # ### end Alembic commands ###
